kind: pipeline
type: kubernetes
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
---

kind: pipeline
type: kubernetes
name: buildtest

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: kevinbacon
      from_secret: DOCKER_USERNAME
    password: pa55word
      from_secret: DOCKER_PASSWORD
    repo: classicsla/pollwedding:tagname
    context: weddingPageLD
    tags: latest
