kind: pipeline
type: kubernetes
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - ls -l
  - tree -L 3

- name: build  
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: classicsla/pollwedding:tagname
    context: weddingPageLD
    tags: latest
