---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nfs-provisioner
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: nfs-provisioner
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/nfs-provisioner
  prune: true
  sourceRef:
    kind: GitRepository
    name: nfs-provisioner
  validation: client

